In [1]:
from src.scan_matching import ICP
from src.icp import icp as py_icp
from src.new_icp import icp as hn_icp
import numpy as np

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [2]:
a = np.array([[0., 0.],
              [0., 2.],
              [1., 3.],
              [2., 2.],
              [2., 0.]])

ang = np.radians(30)
R = np.array([[np.cos(ang), - np.sin(ang)],
              [np.sin(ang), np.cos(ang)]])

t = np.array([1, 1])

b = R @ a.T + t[:, None]
b = b.T

R, t

(array([[ 0.8660254, -0.5      ],
        [ 0.5      ,  0.8660254]]),
 array([1, 1]))

In [3]:
icp = ICP()
icp(a, b, n_iter=20)

(array([[ 0.99999928,  0.001197  ,  0.09114525],
        [-0.001197  ,  0.99999928,  1.04042848],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[1.00000000e+00, 1.00000000e+00],
        [2.22044605e-16, 2.73205081e+00],
        [3.66025404e-01, 4.09807621e+00],
        [1.73205081e+00, 3.73205081e+00],
        [2.73205081e+00, 2.00000000e+00]]))

In [4]:
py_icp(a, b)

(array([[ 0.89544721, -0.44516771,  1.16701807],
        [ 0.44516771,  0.89544721,  0.94043668],
        [ 0.        ,  0.        ,  1.        ]]),
 array([0.97578534, 0.66142086, 0.75391645, 0.66142086, 0.97578534]))

In [5]:
hn_icp(a, b, R_initial=np.eye(2), t_initial=np.zeros(2))

(array([[ 0.99999928,  0.001197  ,  0.09114525],
        [-0.001197  ,  0.99999928,  1.04042848],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[0.09114525, 1.04042848],
        [0.09353924, 3.04042705],
        [1.09473552, 4.03922934],
        [2.0935378 , 3.03803306],
        [2.09114381, 1.03803449]]))

In [7]:
AA = np.array([[-1. , -1.4],
       [-1. ,  0.6],
       [ 0. ,  1.6],
       [ 1. ,  0.6],
       [ 1. , -1.4]])

BB = np.array([[ 0.05358984, -0.89282032],
       [-0.94641016,  0.83923048],
       [-0.94641016,  0.83923048],
       [ 1.78564065,  0.10717968],
       [ 0.05358984, -0.89282032]])

In [8]:
np.sum(AA[..., None] @ BB[:,None, :], axis=0)

array([[ 2.73205081, -0.7320508 ],
       [-1.16076951,  4.41051176]])

In [31]:
c = np.zeros((2,2))

for i in range(5):
  delt = AA[i, np.newaxis].T @ BB[i, np.newaxis]
  print(delt)
  c += delt

c

[[-0.05358984  0.89282032]
 [-0.07502578  1.24994845]]
[[ 0.94641016 -0.83923048]
 [-0.5678461   0.50353829]]
[[ 0.          0.        ]
 [-1.51425626  1.34276877]]
[[1.78564065 0.10717968]
 [1.07138439 0.06430781]]
[[ 0.05358984 -0.89282032]
 [-0.07502578  1.24994845]]


array([[ 2.73205081, -0.7320508 ],
       [-1.16076951,  4.41051176]])

In [9]:
H = np.dot(AA.T, BB)
H

array([[ 2.73205081, -0.7320508 ],
       [-1.16076951,  4.41051176]])

In [35]:
U, S, Vt = np.linalg.svd(H)

In [36]:
np.dot(Vt.T, U.T)

array([[ 0.99820347, -0.05991526],
       [ 0.05991526,  0.99820347]])

In [37]:
U @ Vt

array([[ 0.99820347,  0.05991526],
       [-0.05991526,  0.99820347]])